name: Build and deploy

on: workflow_dispatch

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to google cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          access_token_lifetime: 300s
        
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Authenticate'
        run: |
          gcloud auth configure-docker europe-north1-docker.pkg.dev
      - name: Build
        run: |
          docker build -t europe-north1-docker.pkg.dev/jeff-bot-379007/jeff-bot/jeff-bot:${{ github.sha }} .
      - name: Publish
        run: |
          docker push europe-north1-docker.pkg.dev/jeff-bot-379007/jeff-bot/jeff-bot:${{ github.sha }}

      - name: Deploy
        id: 'deploy'
        run: |
          gcloud compute instances update-container jeff-bot2-vm --zone europe-north1-a --container-image=europe-north1-docker.pkg.dev/jeff-bot-379007/jeff-bot/jeff-bot:${{ github.sha }}
